    // Advanced Space Weather Concepts (Slides 61-70)
    {
      id: 61,
      title: "⚓ Earth's Magnetic Poles",
      content: "Earth's magnetic poles are not exactly at the geographic North and South Poles - and they move over time! The magnetic field can even flip completely every few hundred thousand years.",
      ttsText: "Earth's magnetic poles are not exactly at the geographic North and South Poles - and they move over time! The magnetic field can even flip completely every few hundred thousand years.",
      animation: Magnetosphere3D
    },
    {
      id: 62,
      title: "🌊 Ocean Currents and Earth's Magnetic Field",
      content: "Earth's magnetic field is partly generated by the movement of liquid metal in the outer core. It's like electric currents flowing deep inside our planet!",
      ttsText: "Earth's magnetic field is partly generated by the movement of liquid metal in the outer core. It's like electric currents flowing deep inside our planet!",
      image: "/public/textures/earth.jpg"
    },
    {
      id: 63,
      title: "🌋 Volcanic Rocks and Earth's Magnetic History",
      content: "Scientists study ancient volcanic rocks to learn about Earth's magnetic field in the past. The rocks record the direction of the magnetic field when they cooled!",
      ttsText: "Scientists study ancient volcanic rocks to learn about Earth's magnetic field in the past. The rocks record the direction of the magnetic field when they cooled!",
      animation: ElementarySpaceAdventure3D
    },
    {
      id: 64,
      title: "🌦️ Space Weather vs. Earth Weather",
      content: "Space weather and Earth weather are very different! Earth weather happens in our atmosphere, while space weather comes from the Sun and affects the space around Earth.",
      ttsText: "Space weather and Earth weather are very different! Earth weather happens in our atmosphere, while space weather comes from the Sun and affects the space around Earth.",
      image: "/src/assets/earth-aurora.jpg"
    },
    {
      id: 65,
      title: "🌎 Animals and the Magnetic Field",
      content: "Many animals, like birds, sea turtles, and even some mammals, can sense Earth's magnetic field! They use it to navigate during long migrations.",
      ttsText: "Many animals, like birds, sea turtles, and even some mammals, can sense Earth's magnetic field! They use it to navigate during long migrations.",
      animation: ElementarySpaceAdventure3D
    },
    {
      id: 66,
      title: "📅 The Carrington Event - 1859",
      content: "The biggest space weather event ever recorded happened in 1859. It caused auroras visible worldwide and would have caused major problems if it happened today!",
      ttsText: "The biggest space weather event ever recorded happened in 1859. It caused auroras visible worldwide and would have caused major problems if it happened today!",
      image: "/src/assets/space-weather-impacts.jpg"
    },
    {
      id: 67,
      title: "🌍 Space Weather Around the World",
      content: "Space weather affects the whole world, but some places more than others. Areas near the North and South Poles see more auroras and space weather effects.",
      ttsText: "Space weather affects the whole world, but some places more than others. Areas near the North and South Poles see more auroras and space weather effects.",
      animation: Magnetosphere3D
    },
    {
      id: 68,
      title: "👨‍🚀 Space Weather and Astronauts",
      content: "Astronauts in space need special protection from space weather. They can hide in shielded parts of the space station during strong solar storms.",
      ttsText: "Astronauts in space need special protection from space weather. They can hide in shielded parts of the space station during strong solar storms.",
      image: "/src/assets/space-weather-impacts.jpg"
    },
    {
      id: 69,
      title: "🔬 How Scientists Study Space Weather",
      content: "Scientists use ground-based telescopes, satellites, and computer models to study space weather. They work together around the world to understand and predict it.",
      ttsText: "Scientists use ground-based telescopes, satellites, and computer models to study space weather. They work together around the world to understand and predict it.",
      animation: HighSchoolSpaceAdventure3D
    },
    {
      id: 70,
      title: "🌐 Space Weather and Climate",
      content: "While space weather doesn't directly cause climate change, it can affect Earth's upper atmosphere and may have small effects on our weather patterns.",
      ttsText: "While space weather doesn't directly cause climate change, it can affect Earth's upper atmosphere and may have small effects on our weather patterns.",
      image: "/src/assets/earth-aurora.jpg"
    },

    // Real-world Examples and Conclusion (Slides 71-75)
    {
      id: 71,
      title: "🚀 Future of Space Weather Research",
      content: "Scientists are developing better ways to predict space weather and protect our technology. New missions and instruments will help us understand space weather even better!",
      ttsText: "Scientists are developing better ways to predict space weather and protect our technology. New missions and instruments will help us understand space weather even better!",
      animation: MiddleSchoolSpaceAdventure3D
    },
    {
      id: 72,
      title: "📱 Space Weather Apps",
      content: "There are special apps that can alert you about space weather! They can tell you when aurora might be visible or when satellites might be affected.",
      ttsText: "There are special apps that can alert you about space weather! They can tell you when aurora might be visible or when satellites might be affected.",
      image: "/src/assets/space-weather-impacts.jpg"
    },
    {
      id: 73,
      title: "🎓 Becoming a Space Weather Scientist",
      content: "If you're interested in space weather, you could become a space physicist, astronomer, or engineer who designs protective systems for satellites and power grids!",
      ttsText: "If you're interested in space weather, you could become a space physicist, astronomer, or engineer who designs protective systems for satellites and power grids!",
      animation: HighSchoolSpaceAdventure3D
    },
    {
      id: 74,
      title: "🧠 Test Your Knowledge!",
      content: "Let's see how much you've learned about space weather! Answer this question to test your understanding.",
      ttsText: "Let's see how much you've learned about space weather! Answer this question to test your understanding.",
      interactive: true,
      quiz: {
        question: "What causes solar flares?",
        options: [
          "The Sun getting too hot",
          "Magnetic energy being released in the Sun's atmosphere",
          "Earth's gravity pulling on the Sun",
          "The Sun spinning too fast"
        ],
        correct: 1,
        explanation: "Solar flares happen when magnetic energy is suddenly released in the Sun's atmosphere, creating bright flashes of light!"
      }
    },
    {
      id: 75,
      title: "🌟 Congratulations, Space Weather Explorer!",
      content: "You've completed your space weather adventure! You now know about the Sun, solar flares, CMEs, and how they affect Earth. Keep exploring the amazing world of space science!",
      ttsText: "Congratulations, Space Weather Explorer! You've completed your space weather adventure! You now know about the Sun, solar flares, CMEs, and how they affect Earth. Keep exploring the amazing world of space science!",
      animation: ElementarySpaceAdventure3D
    }
  ];

  useEffect(() => {
    if (slides[currentSlide]?.interactive) {
      setShowQuiz(true);
    } else {
      setShowQuiz(false);
      setQuizAnswer(null);
      setShowQuizResult(false);
    }
  }, [currentSlide]);

  const handleNext = () => {
    if (currentSlide < slides.length - 1) {
      setCurrentSlide(currentSlide + 1);
      stop();
    }
  };

  const handlePrev = () => {
    if (currentSlide > 0) {
      setCurrentSlide(currentSlide - 1);
      stop();
    }
  };

  const handleReset = () => {
    setCurrentSlide(0);
    stop();
  };

  const handlePlay = () => {
    if (!isPlaying) {
      speak(slides[currentSlide].ttsText);
      setIsPlaying(true);
    } else {
      stop();
      setIsPlaying(false);
    }
  };

  const handleQuizAnswer = (index: number) => {
    setQuizAnswer(index);
    setShowQuizResult(true);
  };

  return (
    <div className="container py-8 max-w-4xl mx-auto space-y-8" ref={slideRef}>
      <div className="flex justify-between items-center">
        <h1 className="text-3xl font-bold">Space Weather Adventure</h1>
        <div className="flex gap-2">
          <Button variant="outline" size="icon" onClick={handleReset}>
            <Home className="h-4 w-4" />
          </Button>
          <Button variant="outline" size="icon" onClick={handleReset}>
            <RotateCcw className="h-4 w-4" />
          </Button>
        </div>
      </div>

      <Progress value={(currentSlide + 1) / slides.length * 100} className="h-2" />

      <Card className="shadow-lg">
        <CardContent className="pt-6 min-h-[500px]">
          <div className="flex flex-col space-y-4">
            <h2 className="text-2xl font-bold text-center">{slides[currentSlide].title}</h2>
            
            <div className="min-h-[300px] flex justify-center items-center">
              {slides[currentSlide].animation ? (
                <div className="w-full h-[300px]">
                  {React.createElement(slides[currentSlide].animation)}
                </div>
              ) : slides[currentSlide].image ? (
                <div className="w-full h-[300px] flex justify-center">
                  <img 
                    src={slides[currentSlide].image} 
                    alt={slides[currentSlide].title} 
                    className="max-h-[300px] object-contain" 
                  />
                </div>
              ) : (
                <div className="w-full h-[300px] flex items-center justify-center bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg text-white text-xl font-semibold">
                  Space Weather Interactive
                </div>
              )}
            </div>

            <p className="text-lg">{slides[currentSlide].content}</p>

            {showQuiz && (
              <div className="mt-4 p-4 bg-gray-100 rounded-lg">
                <h3 className="text-xl font-semibold mb-2">{slides[currentSlide].quiz?.question}</h3>
                <div className="space-y-2">
                  {slides[currentSlide].quiz?.options.map((option, index) => (
                    <Button
                      key={index}
                      onClick={() => handleQuizAnswer(index)}
                      variant={quizAnswer === index ? "default" : "outline"}
                      className="w-full justify-start"
                      disabled={showQuizResult}
                    >
                      {option}
                    </Button>
                  ))}
                </div>
                {showQuizResult && (
                  <div className={`mt-4 p-3 rounded-lg ${quizAnswer === slides[currentSlide].quiz?.correct ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                    <p className="font-semibold">
                      {quizAnswer === slides[currentSlide].quiz?.correct ? 'Correct!' : 'Not quite right.'}
                    </p>
                    <p>{slides[currentSlide].quiz?.explanation}</p>
                  </div>
                )}
              </div>
            )}

            <TTSControls
              text={slides[currentSlide].ttsText}
              isPlaying={isPlaying}
              onToggle={handlePlay}
            />
          </div>
        </CardContent>
      </Card>

      <div className="flex justify-between">
        <Button 
          onClick={handlePrev} 
          disabled={currentSlide === 0}
          className="flex items-center gap-2"
        >
          <ChevronLeft className="h-4 w-4" /> Previous
        </Button>
        <Button 
          onClick={handleNext} 
          disabled={currentSlide === slides.length - 1}
          className="flex items-center gap-2"
        >
          Next <ChevronRight className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
};

export default Adventure;