import React from 'react';
import { motion } from 'framer-motion';
import { Card } from './ui/card';
import {
  Telescope,
  Sun,
  Clock,
  ThermometerSun,
  Compass,
  Orbit,
  Moon,
  Rocket,
  MoveHorizontal,
  BarChart4,
  Scale,
  Atom
} from 'lucide-react';

interface FactCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  delay?: number;
}

const FactCard: React.FC<FactCardProps> = ({ icon, title, description, delay = 0 }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: delay * 0.1, duration: 0.5 }}
      className="w-full"
    >
      <Card className="h-full p-5 border-glass bg-glass/30 backdrop-blur-sm hover:bg-glass/40 transition-all duration-300">
        <div className="flex flex-col h-full">
          <div className="text-primary-300 mb-3">{icon}</div>
          <h3 className="text-lg font-semibold mb-2">{title}</h3>
          <p className="text-sm text-muted-foreground">{description}</p>
        </div>
      </Card>
    </motion.div>
  );
};

const SolarSystemFacts: React.FC = () => {
  const facts = [
    {
      icon: <Sun className="w-6 h-6" />,
      title: "The Sun's Energy",
      description: "The Sun produces enough energy in one second to power human civilization for 500,000 years at current consumption rates."
    },
    {
      icon: <Orbit className="w-6 h-6" />,
      title: "The Vastness of Space",
      description: "If the Sun were the size of a basketball, Earth would be the size of a pea about 82 feet away."
    },
    {
      icon: <ThermometerSun className="w-6 h-6" />,
      title: "Extreme Temperatures",
      description: "The coldest planet is not Pluto but Neptune, with winds that can reach 1,200 mph and temperatures of -366°F."
    },
    {
      icon: <Clock className="w-6 h-6" />,
      title: "Time Relativity",
      description: "A day on Venus (243 Earth days) is longer than a year on Venus (225 Earth days)."
    },
    {
      icon: <MoveHorizontal className="w-6 h-6" />,
      title: "Cosmic Speed",
      description: "Our solar system is traveling through the Milky Way at about 515,000 mph, completing one orbit every 230 million years."
    },
    {
      icon: <Scale className="w-6 h-6" />,
      title: "Weight Differences",
      description: "A person weighing 100 pounds on Earth would weigh 38 pounds on Mars and 236 pounds on Jupiter."
    },
    {
      icon: <Telescope className="w-6 h-6" />,
      title: "Telescope Discovery",
      description: "Uranus and Neptune were the first planets discovered with telescopes, in 1781 and 1846 respectively."
    },
    {
      icon: <BarChart4 className="w-6 h-6" />,
      title: "Jupiter's Dominance",
      description: "Jupiter has more mass than all other planets combined, and could fit 1,300 Earths inside it."
    },
    {
      icon: <Moon className="w-6 h-6" />,
      title: "Fascinating Moons",
      description: "There are over 200 moons in our solar system. Saturn's moon Titan has rain, rivers, and seas of liquid methane and ethane."
    },
    {
      icon: <Compass className="w-6 h-6" />,
      title: "Magnetic Mysteries",
      description: "Earth's magnetic field is generated by its molten iron core and protects us from harmful solar radiation."
    },
    {
      icon: <Rocket className="w-6 h-6" />,
      title: "Space Exploration",
      description: "The Voyager 1 spacecraft, launched in 1977, is now in interstellar space and is the most distant human-made object."
    },
    {
      icon: <Atom className="w-6 h-6" />,
      title: "Cosmic Origins",
      description: "Almost all elements heavier than hydrogen and helium were created inside stars and through supernovae explosions."
    },
  ];

  return (
    <div className="my-12">
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-center mb-8"
      >
        <h2 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
          Fascinating Solar System Facts
        </h2>
        <p className="text-muted-foreground mt-2">
          Discover incredible facts about our cosmic neighborhood
        </p>
      </motion.div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
        {facts.map((fact, index) => (
          <FactCard
            key={index}
            icon={fact.icon}
            title={fact.title}
            description={fact.description}
            delay={index}
          />
        ))}
      </div>
    </div>
  );
};

export default SolarSystemFacts;